name: salve-v1
channels:
  # The mac environment closely follows the linux conda environment file, 
  # except for two noticeable differences: no CUDA support and no DEGENSAC support.

  # TO add: mseg_semantic @ git+https://github.com/mseg-dataset/mseg-semantic.git@master
  #
  # for priority order, we prefer pytorch as the highest priority as it supplies
  # latest stable packages for numerous deep learning based methods. conda-forge
  # supplies higher versions of packages like opencv compared to the defaults
  # channel.
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # python essentials
  - python=3.8
  - pip
  # formatting and dev environment
  - black
  - coverage
  - mypy
  - pylint
  - pytest
  # dask and related
  - dask # same as dask[complete] pip distribution
  - python-graphviz
  # core functionality and APIs
  - matplotlib==3.4.2
  - numpy
  - nodejs
  - pandas
  - pillow>=8.0.1
  - scikit-learn
  - seaborn
  # 3rd party algorithms for different modules
  - opencv=4.5.0 # preferring conda-forge's distribution as it provides the latest distribution
  - pytorch
  - torchvision
  # io
  - h5py
  - pip:
    - hydra-core==1.1.0
    - argoverse @ git+https://github.com/argoai/argoverse-api.git@master
    - rdp
    - yacs # for HoHoNet
    - open3d
    - networkx>=2.6.3
    - pytest-cov
