name: salve-v10
channels:
  # for priority order, we prefer pytorch as the highest priority as it supplies
  # latest stable packages for numerous deep learning based methods. conda-forge
  # supplies higher versions of packages like opencv compared to the defaults
  # channel.
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # python essentials
  - python==3.8
  - pip
  # formatting and dev environment
  - black
  - coverage
  - mypy
  - pylint
  - pytest
  # dask and related
  - dask # same as dask[complete] pip distribution
  - python-graphviz
  # core functionality and APIs
  - click
  - matplotlib>=3.4.2
  - numpy
  - nodejs
  - pandas
  - pillow>=8.0.1
  - scikit-learn
  - seaborn
  - shapely
  - tqdm
  # 3rd party algorithms for different modules
  - cudatoolkit=11.3
  - opencv>=4.5.0 # preferring conda-forge's distribution as it provides the latest distribution
  - pytorch
  - torchvision
  # io
  - h5py
  - imageio
  - pip:
    - hydra-core==1.1.0
    - rdp
    - yacs # for HoHoNet
    - open3d
    - networkx>=2.6.3
    - pytest-cov
    - gtsam==4.2a7
    - simplejson
    - colour
    - gtsfm==0.2.0

# conda-forge's matplotlib is missing some backends, so we use pypi's.