

TrainingConfig:
    _target_: afp.training_config.TrainingConfig
    lr_annealing_strategy: poly
    base_lr: 0.001
    weight_decay: 0.0001
    num_ce_classes: 2
    print_every: 10
    poly_lr_power: 0.9
    optimizer_algo: adam
    num_layers: 152
    pretrained: True
    dataparallel: True
    resize_h: 234
    resize_w: 234
    train_h: 224
    train_w: 224
    apply_photometric_augmentation: False
    modalities: ["floor_rgb_texture"]

    cfg_stem: 
    num_epochs: 50
    workers: 15
    batch_size: 256

    #data_root: "/Users/johnlam/Downloads/DGX-rendering-2021_06_25/ZinD_BEV_RGB_only_2021_06_25",
    data_root: /data/johnlam/ZinD_Bridge_API_BEV_2021_10_20_lowres
    layout_data_root: 
    #model_save_dirpath": "/Users/johnlam/Downloads/ZinD_trained_models_2021_06_25",
    model_save_dirpath: /data/johnlam/ZinD_trained_models_2021_10_22
    gpu_ids:
