

TrainingConfig:
    _target_: afp.training_config.TrainingConfig
    lr_annealing_strategy: poly
    base_lr: 0.001
    weight_decay: 0.0001
    num_ce_classes: 2
    print_every: 10
    poly_lr_power: 0.9
    optimizer_algo: adam
    num_layers: 152
    pretrained: True
    dataparallel: True
    resize_h: 234
    resize_w: 234
    train_h: 224
    train_w: 224
    apply_photometric_augmentation: False
    modalities: ["ceiling_rgb_texture", "floor_rgb_texture"]

    cfg_stem: 
    num_epochs: 50
    workers: 25
    batch_size: 256

    data_root: /data/johnlam/Renderings_ZinD_bridge_api_GT_WDO_2021_11_20_SE2_width_thresh0.8
    layout_data_root: 
    #model_save_dirpath": "/Users/johnlam/Downloads/ZinD_trained_models_2021_06_25",
    model_save_dirpath: /data/johnlam/ZinD_trained_models_2021_11_23
    gpu_ids:
